# Generated by Django 6.0.3 on 2026-03-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. B.Sc. CSIT, BCA, BIM",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="e.g. CSIT, BCA", max_length=30, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon string e.g., Monitor",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("date_published", models.DateField(auto_now_add=True)),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Link to official notice if any"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exampaper.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. First Semester", max_length=50),
                ),
                ("number", models.PositiveSmallIntegerField(help_text="e.g. 1")),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="exampaper.department",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("department", "number")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="e.g. CSC109", max_length=50
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250)),
                ("credit_hours", models.PositiveSmallIntegerField(default=3)),
                ("objective", models.TextField(blank=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exampaper.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("semester", "code")},
            },
        ),
        migrations.CreateModel(
            name="SubjectResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Unit 1: Introduction to IT, 2079 Regular Exam Paper",
                        max_length=250,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("syllabus", "Syllabus"),
                            ("note", "Note & Study Material"),
                            ("old_question", "Old Question Paper"),
                            ("solution", "Solution / Guidelines"),
                            ("lab_report", "Lab Report / Practical"),
                            ("assignment", "Assignment / Project"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/%Y/%m/")),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="For old questions (e.g. 2079)", null=True
                    ),
                ),
                (
                    "contributor",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who provided this",
                        max_length=150,
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="exampaper.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
    ]
