# Generated by Django 4.2.29 on 2026-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresource',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True to publish this resource. Handled by admin approval workflow.'),
        ),
        migrations.AlterField(
            model_name='subjectresource',
            name='resource_type',
            field=models.CharField(choices=[('syllabus', 'Syllabus'), ('note', 'Note & Study Material'), ('old_question', 'Old Question Paper'), ('solution', 'Solution / Guidelines'), ('lab_report', 'Lab Report / Practical'), ('assignment', 'Assignment / Project')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='subjectresource',
            index=models.Index(fields=['subject', 'resource_type', 'is_approved'], name='res_subj_type_approved_idx'),
        ),
    ]
