# Generated by Django 6.0.3 on 2026-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exampaper", "0002_add_indexes_fix_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceRequest",
            fields=[],
            options={
                "verbose_name": "Pending Resource Request",
                "verbose_name_plural": "Pending Resource Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exampaper.subjectresource",),
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-date_published"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": ["number"],
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="icon_name",
            field=models.CharField(
                blank=True, help_text="Lucide icon string e.g. Monitor", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="subjectresource",
            name="contributor",
            field=models.CharField(
                blank=True, help_text="Name of the contributing student", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="subjectresource",
            name="title",
            field=models.CharField(
                help_text="e.g. Unit 1: Introduction to IT", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="subjectresource",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bikram Sambat year, e.g. 2080", null=True
            ),
        ),
    ]
