# Generated by Django 4.2.29 on 2026-06-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exampaper", "0003_meta_and_field_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectresource",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Subject Resource",
                "verbose_name_plural": "Subject Resources",
            },
        ),
    ]
