# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0004_alter_subjectresource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresource',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Cached file size to avoid S3 calls', null=True),
        ),
    ]
